# Generated by Django 5.1.6 on 2025-03-15 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0003_remove_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Telefon raqamida faqat raqamlar bo'lishi kerak.", regex='^\\+?[0-9]{1,15}$')]),
        ),
    ]
