# Generated by Django 5.1.6 on 2025-03-15 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0006_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="Telefon raqami +998 formatida bo'lishi kerak va 9 raqamdan iborat bo'lishi lozim.", regex='^\\+998[0-9]{9}$')]),
        ),
    ]
