# Generated by Django 5.1.6 on 2025-03-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0008_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'CustomUser', 'verbose_name_plural': 'CustomUsers'},
        ),
        migrations.AlterModelOptions(
            name='globaluserinfo',
            options={'verbose_name': 'GlobalUserInfo', 'verbose_name_plural': 'GlobalUserInfo'},
        ),
    ]
