# Generated by Django 5.1.6 on 2025-03-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_users', '0009_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaluserinfo',
            name='card_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
