# Generated by Django 5.1.6 on 2025-03-17 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marathon',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marathons', to='exams.category'),
        ),
        migrations.AlterField(
            model_name='marathon',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
