# Generated by Django 5.1.6 on 2025-03-19 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_marathon_category_alter_marathon_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='marathon',
            options={'verbose_name': 'Marathon', 'verbose_name_plural': 'Marathon'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Option'},
        ),
    ]
